[package]
name = "jogo_advinhacao"
version = "0.1.0"
authors = ["senick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.3.14"
